# Generated by Django 2.2.5 on 2019-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190912_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.TextField(default='NONE'),
        ),
    ]
