# Generated by Django 2.2.5 on 2019-09-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190914_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
