# Generated by Django 2.2.5 on 2019-09-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190914_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
