# Generated by Django 2.2.5 on 2019-09-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20190911_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=225)),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete='SET_NULL', to='home.Article')),
            ],
        ),
    ]
