# Generated by Django 2.0 on 2020-11-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('BreifContent', models.TextField()),
                ('Content', models.TextField()),
                ('PublishDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
