# Generated by Django 2.0 on 2020-11-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='BreifContent',
            new_name='BriefContent',
        ),
    ]
