# Generated by Django 2.2.5 on 2019-09-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contacts',
            name='subject',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
