# Generated by Django 2.2.5 on 2019-09-13 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='subject',
            field=models.TextField(default=datetime.datetime(2019, 9, 13, 17, 24, 18, 348587, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
