# Generated by Django 2.2.5 on 2019-09-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190913_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
